- hosts: vps
  gather_facts: no
  tasks:
    - name: Pull la dernière version du dépôt
      git:
        repo: "git@github.com:archiMydi/laravel-docker.git"
        dest: /home/xjeypbqy/www/cours-infra
        version: main
        force: yes

    - name: Installer les dépendances PHP
      command: composer install --prefer-dist
      args:
        chdir: /home/xjeypbqy/www/cours-infra

    - name: Lancer les migrations
      command: php artisan migrate --force
      args:
        chdir: /home/xjeypbqy/www/cours-infra
